name: Package Main

on:
  push:
    branches:
      - main

jobs:
  log:
    name: Log commit message
    runs-on: ubuntu-latest
    steps:
      - run: echo "Author of PR is ${{ github.event.pull_request.user.login }} || ${{ github.actor }}"
      - run: echo "Commit message  ${{ github.event.head_commit.message }} "
  conditionalog:
    name: Log Conditionally
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore(release):')"
    steps:
      - run: echo "Expected 'chore(release)' message  ${{ github.event.head_commit.message }} "
      - run: echo "End conditional log"
